language: java
jdk:
  - openjdk11

branches:
  only:
    - main
before_script:
  - cd {freelec-springboot2-webservice}/

before_install:
  - chmod+x./gradlew

#Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

#CI실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      login-@nate.com